### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by aganov** [scalefocus/virusafe-android#13]
Why this app is collecting so much personal data? Singapore's government open sourced their contact-tracing protocol, based just on BLE. Can be found here https://bluetrace.io/ and here https://github.com/OpenTrace-community

BlueTrace protocol is focused on privacy

> The only personally-identifiable information collected is a phone number, which is securely stored by the health authority.

**Comment by s-yanev** [comment]
Hello in **The Terms of Use** there is detailed description who administers your personal data, why it is collected, for what it is used and where it is provided. 

The data is available only to the Ministry of Health and the competent authorities which are figting against the spread of the infection.

I am cloasing this issue, since all of the needed information can be found in **The Terms of Use** in the app or in the [locales](https://github.com/scalefocus/virusafe-android/tree/develop/locale-example/Common) folder in the repo.
